---
name: Build Docker Image

on:
  pull_request:
    branches:    
      - main
      - master

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: |
          cd node 
          echo node
      # - name: Push docker image
      #   run: |
      #     docker tag temp/build cahyakargo/kargo:latest
      #     docker tag temp/build cahyakargo/kargo:${{ github.sha }}
      #     docker push cahyakargo/kargo:latest
      #     docker push cahyakargo/kargo:${{ github.sha }}
