---
name: Build Docker Image

on: 
  pull_request:
    branches:
      - master

jobs:
  test:
    name: Build Application
    runs_on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run : echo hi