---
name: Build Docker Image

on:
  push:
    branches:    
      - main
      - master

jobs:
  build:
    name: Build Application
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: |
          cd node 
          docker build -t temp/build .
      - name: Push docker image
        run: |
          echo ${{ secrets.CI_REGISTRY_PASSWORD }} | docker login --username ${{ secrets.CI_REGISTRY_USER }} --password-stdin
          docker tag temp/build cahyakargo/kargo:${{ github.sha }}
          docker push cahyakargo/kargo:${{ github.sha }}
