---
name: Run Unit Tests

on: push

jobs:
  deploy:
    name: Testing Application
    runs_on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - with: 
          target_path: ./node
      - name: testing
        run: | 
          npm install
          npm test