---
name: Build Docker Image

on: push

jobs:
  deploy:
    name: Build Application
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - with: 
          target_path: ./node
        run: npm test
