---
name: Run Unit Tests

on: push

jobs:
  deploy:
    name: Testing Application
    runs_on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: testing
        run: | 
          cd node
          npm install
          npm test