---
name: Run Unit Tests

on: pull_request

jobs:
  test:
    name: Testing Application
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: testing
        run: | 
          cd node
          npm install
          npm test